### ISSUE TITLE
`nb q -t TAG` matches TAG but also any tag *beginning with* TAG

### ISSUE THREAD

**Issue by 0ion9** [xwmx/nb#326]
Hi, I'm recently experimenting with nb and I found this behaviour which I think is an inappropriate default, if the assumption that search utilities will generally use regexps to describe the pattern to match is valid.
Maybe there is a way to configure this, in which case feel free to correct me.

`nb -q -t TAG` will also match any tag beginning with TAG.
For example, suppose I create a new note and tag it `#markdown`.
`nb -q -t markdown` will correctly find this note.
but, `nb -q -t mark` will also find this note, and it shouldn't (It would hardly be surprising if I were also to need to tag an article as being related to a person named Mark, and then search for that later)

If I want to ask for exactly and only the tag 'markdown', then I must append `\b` to the query -- which in most shells also means I must quote the tag name : `nb q -t 'mark\b'`. This is somewhat inconvenient, especially given that I can often-but-not-always get away with forgetting to do this.
It seems to me that appending `\b` to tag search patterns by default [^1] would be more reliable, and then, anyone who really DOES want to search for 'all tags beginning with FOO, including exactly FOO' would append '\w*' to their tag: `nb q -t 'FOO\w*' `

EDIT: for now, the simplest workaround I've found is to ignore the `-t` interface and build the regexps myself (fish shell script follows):
```fish
nb q (printf '(^|\\\b)#%s\\\b\n' (nb q --tags | fzf -m | string sub -s 2))
```

[^1]: for anyone reading this who doesn't know regex, `\b` means 'match on a word boundary', which is more strict but still not fully exact -- for example searching 'mark' would not match 'markdown' but it WOULD match 'mark-up', since the `k-` transition counts as a word boundary. I view that as probably unsolvable, since for example it isn't unreasonable to put tags `(#in #brackets #like #this)` and in that scenario the `)` really isn't part of the tag name.

**Comment by xwmx** [comment]
@0ion9 Thanks for the heads up. This was updated in the repository in July and should now be resolved as of version 7.14.0 and higher. Please let me know if you run into any more issues with it. Thanks!

**Comment by cygaj** [comment]
Hello! I am still experiencing this issue in ~`nb 7.24.1`~ (EDIT: just updated to `7.25.0` but am getting the same output). Am I doing something wrong?
```
$ nb a "testing tags #art"
Added: [161] 20260223160728.md

$ nb a "testing tags #artwork"
Added: [162] 20260223160739.md

$ nb q -l -t art
[161] 20260223160728.md · "testing tags #art"
[162] 20260223160739.md · "testing tags #artwork"
```
```
$ nb add --tags one "another tag test"
Added: [163] 20260223161043.md

$ nb add --tags onetwo "another tag test 2"
Added: [164] 20260223161058.md

$ nb q -l -t one
[163] 20260223161043.md · "another tag test"
[164] 20260223161058.md · "another tag test 2"
```
